### ISSUE TITLE
Lingering puppeteer processes cause penthouse to timeout and build to fail

### ISSUE THREAD

**Issue by psm0dev0tst** [Tom-Bonnike/netlify-plugin-inline-critical-css#5] opened 2020-05-25 06:38 UTC
Awesome plugin!
It was working fine until it starting causing problems for my builds.

I'm unclear how this happened or how to resolve it, but I'm currently in a situation where my builds fail because of lingering puppeteer processes.
I can remove the plugin and proceed, but there's something up with this plugin causing puppeteer to linger in certain cases.

Here's what is shown at the end of the build.

> 2:17:19 AM: ** WARNING **  
> 2:17:19 AM: There are some lingering processes even after the build process finished: 
> 2:17:19 AM: USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> 2:17:19 AM: buildbot    1548  0.1  0.1 447788 48476 ?        S    06:16   0:00 /opt/build/repo/node_modules/netlify-plugin-inline-critical-css/node_modules/puppeteer/.local-chromium/linux-650583/chrome-linux/chrome --type=zygote --no-sandbox --headless --headless
> 2:17:19 AM: buildbot    1561  0.6  0.3 555216 96252 ?        Sl   06:16   0:00 /opt/build/repo/node_modules/netlify-plugin-inline-critical-css/node_modules/puppeteer/.local-chromium/linux-650583/chrome-linux/chrome --type=gpu-process --field-trial-handle=4489240811974593649,7639743241185319030,131072 --enable-features=NetworkService,NetworkServiceInProcess --disable-features=BlinkGenPropertyTrees,TranslateUI,site-per-process --no-sandbox --disable-breakpad --headless --headless --gpu-preferences=KAAAAAAAAAAgAAAgAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --service-request-channel-token=1495995070197870940
> 2:17:19 AM: Our builds do not kill your processes automatically, so please make sure
> 2:17:19 AM: that nothing is running after your build finishes, or it will be marked as
> 2:17:19 AM: failed since something is still running.

And the particular log as it relates to this great plugin:

> 2:17:07 AM: ┌────────────────────────────────────────────────────┐
> 2:17:07 AM: │ Plugin "netlify-plugin-inline-critical-css" failed │
> 2:17:07 AM: └────────────────────────────────────────────────────┘
> 2:17:07 AM: ​
> 2:17:07 AM:   Error message
> 2:17:07 AM:   Error: Failed to inline critical CSS.
> 2:17:07 AM:   Penthouse timed out after 30s.
> 2:17:07 AM: ​
> 2:17:07 AM:   Plugin details
> 2:17:07 AM:   Package:        netlify-plugin-inline-critical-css
> 2:17:07 AM:   Version:        1.0.4
> 2:17:07 AM:   Repository:     git+https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css.git
> 2:17:07 AM:   npm link:       https://www.npmjs.com/package/netlify-plugin-inline-critical-css
> 2:17:07 AM:   Report issues:  https://github.com/Tom-Bonnike/netlify-plugin-inline-critical-css/issues
> 2:17:07 AM: ​
> 2:17:07 AM:   Error location
> 2:17:07 AM:   In "onPostBuild" event in "netlify-plugin-inline-critical-css" from netlify.toml and package.json
> 2:17:07 AM:       at Timeout.setTimeout (/node_modules/netlify-plugin-inline-critical-css/node_modules/penthouse/lib/core.js:341:16)
> 2:17:07 AM: ​
> 2:17:07 AM:   Resolved config
> 2:17:07 AM:   build:
> 2:17:07 AM:     command: 'npm-run-all build:css build:js build:html'
> 2:17:07 AM:     environment:
> 2:17:07 AM:     functions: /opt/build/repo/functions
> 2:17:07 AM:     publish: /opt/build/repo/_11ty_output
> 2:17:07 AM:   plugins:
> 2:17:07 AM:     - inputs:
> 2:17:07 AM:         buildDir: _11ty_output
> 2:17:07 AM:       origin: config
> 2:17:07 AM:       package: '@netlify/plugin-sitemap'
> 2:17:07 AM:     - origin: config
> 2:17:07 AM:       package: netlify-plugin-search-index
> 2:17:07 AM:     - inputs:
> 2:17:07 AM:         dimensions:
> 2:17:07 AM:           - height: 480
> 2:17:07 AM:             width: 320
> 2:17:07 AM:           - height: 896
> 2:17:07 AM:             width: 414
> 2:17:07 AM:           - height: 1080
> 2:17:07 AM:             width: 1920
> 2:17:07 AM:         extract: false
> 2:17:07 AM:         minify: true
> 2:17:07 AM:       origin: config
> 2:17:07 AM:       package: netlify-plugin-inline-critical-css
> 2:17:07 AM:     - inputs:
> 2:17:07 AM:         checkPaths:
> 2:17:07 AM:           - /
> 2:17:07 AM:           - /articles/
> 2:17:07 AM:           - /cleaning-your-mask/
> 2:17:07 AM:         resultMode: warn
> 2:17:07 AM:       origin: config
> 2:17:07 AM:       package: netlify-plugin-a11y

Do you know of a way to kill the puppeteer process in Netlify?

**Comment by psm0dev0tst** [comment] 2020-05-25 06:47
Removing the plugins from the netlify.toml, redeploying, and then adding the plugins again did the trick for now.

**Comment by Tom-Bonnike** [comment] 2020-05-25 09:01
Aw, sorry about the troubles and thank you for taking time to report this.
I’m not really sure what happened to be honest, but please let me know if it starts happening again after you re-enabled the plugin.

Maybe @ehmicky has an idea/might be interested in this.

> 2:17:19 AM: Our builds do not kill your processes automatically, so please make sure
> 2:17:19 AM: that nothing is running after your build finishes, or it will be marked as
> 2:17:19 AM: failed since something is still running.

☝️ should I be doing something about this?

**Comment by ehmicky** [comment] 2020-05-25 12:10
If a Build plugin creates child processes, it is difficult for Netlify to track those and automatically clean them up. At the moment, Build plugins are responsible for cleaning those up.

If a Build plugin exits but does not terminate its child processes, the warning above is shown. The solution would be to ensure any child process is terminated when the plugin stops using either `try`/`cache` blocks or the `onEnd` (error or success), `onError` (error only), `onSuccess` (success only) event handlers.

In your case, `puppeteer` (through `critical > penthouse`) is spawning an instance of `chrome`. It seems from the logs that `chrome` keeps running even after this plugin stopped. Does `critical` has a cleanup function to ensure `chrome` stops running? If so, it should be run in the `catch` block of `onPostBuild`.

**Comment by Tom-Bonnike** [comment] 2020-05-26 12:03
OK, that makes total sense. I investigated a bit and it seems like penthouse handles errors/exits by closing the puppeteer browser, which should exit the `chrome` instance.

---

I found something in the [puppeteer troubleshooting doc](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md) about docker that might be of interest, @ehmicky:
> [dumb-init](https://github.com/Yelp/dumb-init) is worth checking out if you're experiencing a lot of zombies Chrome processes sticking around. There's special treatment for processes with PID=1, which makes it hard to terminate Chrome properly in some cases (e.g. in Docker).

Since the Netlify build images are using Docker, do you think that’s relevant? I don’t think there’s any other plugin relying on puppeteer right now, but if you know of one, it’s worth checking if they have this issue, too.

I’m really not familiar with Docker, so I don’t know where to look on https://github.com/netlify/build-image, this PID 1 kinda seems like a good culprit though? 
Apparently [docker’s --init flag](https://docs.docker.com/engine/reference/run/#specify-an-init-process) does the same as `dumb-init` but neither seem to be used.

I see from the logs posted by OP that chrome is using PID 1548 though, so this might entirely be irrelevant.

---

If you think the above is not relevant to this issue, it’s possible that the issue is caused by this plugin running critical/penthouse concurrently on multiple pages and messing up penthouse’s error/exit handling (it does have some logic to re-use the same browser when ran multiple times though, so I’m assuming it’s also exiting this browser properly and the code seems to make sense…).
A possible solution to this would be to configure `penthouse`’s puppeteer browser by passing the penthouse option: `{ penthouse: { getBrowser: () => { … } } }` and making sure the browser/chromium is closed on error.
Somehow related: https://github.com/puppeteer/puppeteer/issues/1825#issue-289240651

**Comment by ehmicky** [comment] 2020-05-26 12:26
On Unix (which Netlify uses in production), if the parent of a background child process ends, that child process becomes an [orphan process](https://en.wikipedia.org/wiki/Orphan_process). Its new parent becomes init (PID 1). I think this is how Unix is meant to work, and changing the `init` system (e.g. with `dumb-init` or alternative systems) is most likely to break many builds, since this is quite a fundamental part of the OS.

The solution to this is usually to make sure parent processes terminate their background child processes. Unless they intend for those to outlive them, but that does not seem the case here.

I am not completely sure whether [the section on Docker](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker) for puppeteer is relevant or not for Netlify. Namely, [we are using `ubuntu:16.04`](https://github.com/netlify/build-image/blob/30f629161c0736b1a3ecd8b418e5eeffab5c0faf/Dockerfile#L1). Usually, problems occur when using Alpine, `node:*-slim`, etc. which are missing some system dependencies (both of those are the ones mentioned in that document). I am assuming, since puppeteer does seem to run, the `chromium` dependency might be available, so we don't have to run those instructions? I am not sure at all here.

There is a chance that running `penthouse` several times in parallel is messing up with the cleanup indeed, but I am not sure about this either.

(Tagging @mheffner @Benaiah @vbrown608 who might have additional thoughts on this).

**Comment by mheffner** [comment] 2020-05-31 15:07
The lingering process problem is something we are looking at better ways to handle, both by trying to clean them up and also reducing the likelihood that they cause a build failure when they happen.

This is not at all an official solution, but I threw together a plugin the other day that may provide a stopgap solution. It will try to locate lingering processes and kill them directly at the end of a build process. This should remove them before that lingering process warning message is printed. If this helps, it would be useful to know for further debugging of this problem: https://github.com/mheffner/netlify-plugin-process-cleanup

I think the ideal solution here would be for puppeteer to cleanup the chrome processes or possibly use some of the workarounds described in the [issue](https://github.com/puppeteer/puppeteer/issues/1825#), to eliminate the chance of them lingering. On Netlify's side we are continuing to look at options to handle this, as it is a persistent problem in several frameworks.

**Comment by Tom-Bonnike** [comment] 2020-06-19 16:21
Did you somehow notice this happening @ehmicky in projects using this plugin? Otherwise I think I’ll close, removing the parallelization probably fixed it 😅

**Comment by ehmicky** [comment] 2020-06-19 16:29
This is still happening. The following graph is showing instances of build failing due to the `Penthouse timed out after 30s.` error in the last 30 days:

![penthouse](https://user-images.githubusercontent.com/8136211/85156647-a7309080-b25a-11ea-9337-76d4cdea7cf2.png)

The smallest bar is 1 instance, the highest is 4 instances (within an 8 hours interval).

Note: those are mostly different Sites.

**Comment by Tom-Bonnike** [comment] 2020-06-19 16:40
I’ll try to:
- increase penthouse’s timeout to 120s (unlikely this will help, but it could make sense, some pages could take longer than 30s to load, it’s also possible there is a bug in critical/penthouse, apparently 1 known is with `meta` refresh tags…)
- force critical’s `concurrency` option to 1, noticed it defaults to Infinity, it actually still runs the multiple screen dimensions in parallel on the same page, someone mentioned similar issues disappeared after they forced it to 1.

Will be released in 1.1.3.

**Comment by Tom-Bonnike** [comment] 2020-07-06 19:33
@ehmicky could you share the same error graph again pls?

**Closed as completed** 2021-02-15 12:47 UTC
Labels: external-bug

**Comment by djibe** [comment] 2022-05-22 20:48
Hi,

just to share.

I recently had the same build crash error: ` Error: Failed to inline critical CSS. Penthouse timed out after 120s.`

I confirm that you have to disable netlify-plugin-inline-critical-css, launch build and wait until deploy.
Then re-enable netlify-plugin-inline-critical-css back and send a new build.

Enjoy
